name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy frontend to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            echo "Starting frontend deployment..."

            cd /home/ubuntu/ecomm-project/ecomm-react

            echo "Pulling latest frontend code..."
            git pull origin master

            echo "Installing dependencies..."
            npm install

            echo "Building React application..."
            npm run build

            echo "Copying build files to Nginx..."
            sudo rm -rf /var/www/ecomm-project/*
            sudo cp -r build/* /var/www/ecomm-project/

            echo "Reloading Nginx..."
            sudo systemctl reload nginx

            echo "Frontend deployment completed successfully."
